# Generated by Django 4.2.29 on 2026-03-05 02:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='LongTermMemory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frequent_vendors', models.JSONField(blank=True, default=list)),
                ('preferred_period', models.CharField(blank=True, max_length=50, null=True)),
                ('preferred_chart_type', models.CharField(blank=True, max_length=50, null=True)),
                ('favorite_categories', models.JSONField(blank=True, default=list)),
                ('total_queries', models.IntegerField(default=0)),
                ('total_uploads', models.IntegerField(default=0)),
                ('last_filters', models.JSONField(blank=True, default=dict)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='agent_memory', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='GovernanceLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('TOOL_CALL', 'Tool Call'), ('DATA_ACCESS', 'Data Access'), ('EXPORT', 'Export'), ('ANALYTICS', 'Analytics'), ('RECEIPT_UPLOAD', 'Receipt Upload'), ('POLICY_VIOLATION', 'Policy Violation')], max_length=30)),
                ('status', models.CharField(choices=[('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('FLAGGED', 'Flagged')], max_length=15)),
                ('tool_name', models.CharField(blank=True, max_length=100, null=True)),
                ('input_data', models.JSONField(blank=True, default=dict)),
                ('output_data', models.JSONField(blank=True, default=dict)),
                ('rejection_reason', models.TextField(blank=True, null=True)),
                ('confidence_score', models.FloatField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('schema_valid', models.BooleanField(default=True)),
                ('role_permitted', models.BooleanField(default=True)),
                ('scope_enforced', models.BooleanField(default=True)),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='agent.chatsession')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='governance_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('user', 'User'), ('agent', 'Agent'), ('tool', 'Tool'), ('system', 'System')], max_length=10)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('agent_state', models.CharField(blank=True, choices=[('IDLE', 'Idle'), ('INTENT_CLASSIFICATION', 'Intent Classification'), ('TOOL_SELECTION', 'Tool Selection'), ('TOOL_EXECUTION', 'Tool Execution'), ('OUTPUT_VALIDATION', 'Output Validation'), ('MEMORY_UPDATE', 'Memory Update'), ('RESPONSE', 'Response')], max_length=50, null=True)),
                ('tools_used', models.JSONField(blank=True, default=list)),
                ('tool_outputs', models.JSONField(blank=True, default=dict)),
                ('confidence_score', models.FloatField(blank=True, null=True)),
                ('reasoning_trace', models.JSONField(blank=True, default=list)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='agent.chatsession')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
