from openpyxl import Workbook
from openpyxl.styles import Font, PatternFill, Alignment, Border, Side
from openpyxl.chart import BarChart, LineChart, PieChart, Reference
from openpyxl.utils.dataframe import dataframe_to_rows
import pandas as pd
import matplotlib.pyplot as plt
from io import BytesIO
from openpyxl.drawing.image import Image as XLImage
from datetime import datetime
from typing import Dict, List, Any
import os

class ExcelReportBuilder:
    
    # Brand colors
    HEADER_COLOR = "1F4788"  # Dark blue
    SUBHEADER_COLOR = "5B9BD5"  # Light blue
    ACCENT_COLOR = "70AD47"  # Green
    ALT_ROW_COLOR = "F2F2F2"  # Light gray
    
    def __init__(self, company_name: str = "ExpenseAI"):
        self.wb = Workbook()
        self.company_name = company_name
        self.ws = self.wb.active
        
    def create_report(
        self,
        data: pd.DataFrame,
        summary_stats: Dict,
        chart_config: Dict,
        metadata: Dict,
        options: Dict
    ) -> BytesIO:
        """
        Main method to create complete Excel report
        """
        # Remove default sheet
        if "Sheet" in self.wb.sheetnames:
            del self.wb["Sheet"]
        
        # Create sheets based on options
        if options.get('include_summary', True):
            self._create_executive_summary(summary_stats, chart_config, metadata)
        
        if options.get('include_raw_data', True):
            self._create_detailed_data_sheet(data)
        
        if options.get('include_pivot', False):
            self._create_pivot_sheet(data)
        
        if options.get('include_metadata', True):
            self._create_metadata_sheet(metadata)
        
        # Save to BytesIO
        output = BytesIO()
        self.wb.save(output)
        output.seek(0)
        
        return output
    
    def _create_executive_summary(self, stats: Dict, chart_config: Dict, metadata: Dict):
        """
        Create executive summary sheet
        """
        ws = self.wb.create_sheet("Executive Summary", 0)
        
        # Header section
        ws.merge_cells('A1:F1')
        header_cell = ws['A1']
        header_cell.value = self.company_name
        header_cell.font = Font(size=20, bold=True, color="FFFFFF")
        header_cell.fill = PatternFill(start_color=self.HEADER_COLOR, 
                                       end_color=self.HEADER_COLOR, 
                                       fill_type="solid")
        header_cell.alignment = Alignment(horizontal='center', vertical='center')
        ws.row_dimensions[1].height = 30
        
        # Report title
        ws.merge_cells('A2:F2')
        title_cell = ws['A2']
        title_cell.value = metadata.get('report_title', 'Financial Report')
        title_cell.font = Font(size=16, bold=True)
        title_cell.alignment = Alignment(horizontal='center')
        
        # Report metadata
        row = 4
        ws[f'A{row}'] = "Generated By:"
        ws[f'B{row}'] = metadata.get('user', 'System')
        row += 1
        ws[f'A{row}'] = "Date:"
        ws[f'B{row}'] = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
        row += 1
        ws[f'A{row}'] = "Query:"
        ws[f'B{row}'] = metadata.get('query_text', 'N/A')
        
        # Summary statistics
        row += 2
        ws.merge_cells(f'A{row}:F{row}')
        summary_header = ws[f'A{row}']
        summary_header.value = "Summary Statistics"
        summary_header.font = Font(size=14, bold=True, color="FFFFFF")
        summary_header.fill = PatternFill(start_color=self.SUBHEADER_COLOR,
                                          end_color=self.SUBHEADER_COLOR,
                                          fill_type="solid")
        summary_header.alignment = Alignment(horizontal='center')
        
        row += 1
        for key, value in stats.items():
            ws[f'A{row}'] = key.replace('_', ' ').title()
            ws[f'B{row}'] = value
            ws[f'A{row}'].font = Font(bold=True)
            
            # Format currency
            if isinstance(value, (int, float)) and 'amount' in key.lower():
                ws[f'B{row}'].number_format = '₱#,##0.00'
            
            row += 1
        
        # Add chart if available
        if chart_config and chart_config.get('chart_type'):
            row += 2
            chart_img = self._create_chart_image(chart_config)
            if chart_img:
                img = XLImage(chart_img)
                img.width = 480
                img.height = 300
                ws.add_image(img, f'A{row}')
        
        # Auto-fit columns
        for column in ws.columns:
            max_length = 0
            column_letter = column[0].column_letter
            for cell in column:
                if cell.value:
                    max_length = max(max_length, len(str(cell.value)))
            ws.column_dimensions[column_letter].width = min(max_length + 2, 50)
    
    def _create_detailed_data_sheet(self, data: pd.DataFrame):
        """
        Create detailed transactions sheet with filters
        """
        ws = self.wb.create_sheet("Detailed Transactions")
        
        # Add header
        ws.merge_cells('A1:H1')
        header = ws['A1']
        header.value = "Transaction Details"
        header.font = Font(size=14, bold=True, color="FFFFFF")
        header.fill = PatternFill(start_color=self.HEADER_COLOR,
                                  end_color=self.HEADER_COLOR,
                                  fill_type="solid")
        header.alignment = Alignment(horizontal='center')
        
        # Add data
        start_row = 3
        for r_idx, row in enumerate(dataframe_to_rows(data, index=False, header=True), start=start_row):
            for c_idx, value in enumerate(row, start=1):
                cell = ws.cell(row=r_idx, column=c_idx, value=value)
                
                # Style header row
                if r_idx == start_row:
                    cell.font = Font(bold=True, color="FFFFFF")
                    cell.fill = PatternFill(start_color=self.SUBHEADER_COLOR,
                                           end_color=self.SUBHEADER_COLOR,
                                           fill_type="solid")
                    cell.alignment = Alignment(horizontal='center')
                else:
                    # Alternating row colors
                    if r_idx % 2 == 0:
                        cell.fill = PatternFill(start_color=self.ALT_ROW_COLOR,
                                               end_color=self.ALT_ROW_COLOR,
                                               fill_type="solid")
                    
                    # Format currency columns
                    if 'amount' in str(data.columns[c_idx-1]).lower():
                        cell.number_format = '₱#,##0.00'
                    
                    # Format date columns
                    if 'date' in str(data.columns[c_idx-1]).lower():
                        cell.number_format = 'yyyy-mm-dd'
        
        # Add filters
        ws.auto_filter.ref = ws.dimensions
        
        # Freeze panes
        ws.freeze_panes = ws['A4']
        
        # Auto-fit columns
        for column in ws.columns:
            max_length = 0
            column_letter = column[0].column_letter
            for cell in column:
                if cell.value:
                    max_length = max(max_length, len(str(cell.value)))
            ws.column_dimensions[column_letter].width = min(max_length + 2, 50)
    
    def _create_pivot_sheet(self, data: pd.DataFrame):
        """
        Create pivot table sheet
        """
        ws = self.wb.create_sheet("Pivot Analysis")
        
        # Category breakdown
        if 'category' in data.columns and 'total_amount' in data.columns:
            pivot = data.groupby('category')['total_amount'].agg(['sum', 'count', 'mean'])
            pivot.columns = ['Total Amount', 'Transaction Count', 'Average Amount']
            
            # Add header
            ws['A1'] = "Expenses by Category"
            ws['A1'].font = Font(size=14, bold=True)
            
            # Add data
            for r_idx, row in enumerate(dataframe_to_rows(pivot, index=True, header=True), start=3):
                for c_idx, value in enumerate(row, start=1):
                    cell = ws.cell(row=r_idx, column=c_idx, value=value)
                    if r_idx == 3:
                        cell.font = Font(bold=True)
                    elif c_idx > 1 and isinstance(value, (int, float)):
                        cell.number_format = '₱#,##0.00'
    
    def _create_metadata_sheet(self, metadata: Dict):
        """
        Create audit metadata sheet
        """
        ws = self.wb.create_sheet("Audit Metadata")
        
        ws['A1'] = "Export Audit Log"
        ws['A1'].font = Font(size=14, bold=True)
        
        row = 3
        for key, value in metadata.items():
            ws[f'A{row}'] = key.replace('_', ' ').title()
            ws[f'B{row}'] = str(value)
            ws[f'A{row}'].font = Font(bold=True)
            row += 1
        
        # Auto-fit
        ws.column_dimensions['A'].width = 30
        ws.column_dimensions['B'].width = 50
    
    def _create_chart_image(self, chart_config: Dict) -> BytesIO:
        """
        Create chart image using matplotlib
        """
        try:
            chart_type = chart_config.get('chart_type', 'bar')
            labels = chart_config.get('labels', [])
            values = chart_config.get('values', [])
            title = chart_config.get('title', 'Chart')
            
            fig, ax = plt.subplots(figsize=(8, 5))
            
            if chart_type == 'bar':
                ax.bar(labels, values, color=f'#{self.ACCENT_COLOR}')
            elif chart_type == 'line':
                ax.plot(labels, values, marker='o', color=f'#{self.ACCENT_COLOR}')
            elif chart_type == 'pie':
                ax.pie(values, labels=labels, autopct='%1.1f%%')
            
            ax.set_title(title, fontsize=14, fontweight='bold')
            plt.xticks(rotation=45, ha='right')
            plt.tight_layout()
            
            img_buffer = BytesIO()
            plt.savefig(img_buffer, format='png', dpi=150, bbox_inches='tight')
            img_buffer.seek(0)
            plt.close()
            
            return img_buffer
        except Exception as e:
            print(f"Chart creation error: {e}")
            return None